-- ============================================================
-- SSN ELITE — FIX MISSING LIVE RBAC & SITE SETTINGS TABLE
-- Target: Live Supabase PostgreSQL Database (pnxnwtrozxxqoofxutci)
-- 
-- SAFE INCREMENTAL MIGRATION:
--  - Does NOT drop or recreate existing production tables
--  - Does NOT delete products, blogs, lab reports, enquiries, storage, or users
--  - Creates public.admin_users with RLS
--  - Creates public.is_admin() SECURITY DEFINER function
--  - Creates public.site_settings with RLS (public SELECT, admin write)
--  - Seeds initial site_settings if empty
--  - Reloads PostgREST schema cache
-- ============================================================

-- ------------------------------------------------------------
-- 1. CREATE admin_users REGISTRY
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.admin_users (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Enable Row Level Security
ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------
-- 2. CREATE is_admin() SECURITY DEFINER FUNCTION
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.admin_users
    WHERE id = auth.uid()
  )
  OR (
    coalesce((auth.jwt() -> 'app_metadata' ->> 'role'), '') = 'admin'
  );
$$;

-- Grant execution permissions on is_admin()
REVOKE EXECUTE ON FUNCTION public.is_admin() FROM public;
GRANT EXECUTE ON FUNCTION public.is_admin() TO anon, authenticated, service_role;

-- Policy for admin_users: Only existing admins can view the admin registry
DROP POLICY IF EXISTS "Allow admin read admin_users" ON public.admin_users;
CREATE POLICY "Allow admin read admin_users"
  ON public.admin_users FOR SELECT
  TO authenticated
  USING (public.is_admin());

DROP POLICY IF EXISTS "Allow admin manage admin_users" ON public.admin_users;
CREATE POLICY "Allow admin manage admin_users"
  ON public.admin_users FOR ALL
  TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

-- ------------------------------------------------------------
-- 3. CREATE site_settings TABLE
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.site_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instagram_url TEXT,
  instagram_enabled BOOLEAN NOT NULL DEFAULT true,
  facebook_url TEXT,
  facebook_enabled BOOLEAN NOT NULL DEFAULT true,
  linkedin_url TEXT,
  linkedin_enabled BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Enable Row Level Security
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;

-- Explicit permissions for PostgREST API roles
GRANT ALL ON TABLE public.site_settings TO anon, authenticated, service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.admin_users TO anon, authenticated, service_role;

-- Public can only SELECT site_settings
DROP POLICY IF EXISTS "Allow public select on site_settings" ON public.site_settings;
CREATE POLICY "Allow public select on site_settings"
  ON public.site_settings FOR SELECT
  USING (true);

-- Admin can INSERT site_settings
DROP POLICY IF EXISTS "Allow admin insert on site_settings" ON public.site_settings;
CREATE POLICY "Allow admin insert on site_settings"
  ON public.site_settings FOR INSERT
  TO authenticated
  WITH CHECK (public.is_admin());

-- Admin can UPDATE site_settings
DROP POLICY IF EXISTS "Allow admin update on site_settings" ON public.site_settings;
CREATE POLICY "Allow admin update on site_settings"
  ON public.site_settings FOR UPDATE
  TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

-- Admin can DELETE site_settings
DROP POLICY IF EXISTS "Allow admin delete on site_settings" ON public.site_settings;
CREATE POLICY "Allow admin delete on site_settings"
  ON public.site_settings FOR DELETE
  TO authenticated
  USING (public.is_admin());

-- ------------------------------------------------------------
-- 4. INSERT INITIAL DEFAULT SITE SETTINGS (IF EMPTY)
-- ------------------------------------------------------------
INSERT INTO public.site_settings (
  instagram_url,
  instagram_enabled,
  facebook_url,
  facebook_enabled,
  linkedin_url,
  linkedin_enabled
)
SELECT 
  'https://www.instagram.com/ssnindiaelite/',
  true,
  'https://facebook.com/ssnelite',
  true,
  'https://linkedin.com/company/ssnelite',
  true
WHERE NOT EXISTS (
  SELECT 1 FROM public.site_settings
);

-- ------------------------------------------------------------
-- 5. RELOAD POSTGREST SCHEMA CACHE
-- ------------------------------------------------------------
NOTIFY pgrst, 'reload schema';
